/*
Even Fibonacci numbers
Submit

Problem 2
Each new term in the Fibonacci sequence is generated by adding 
the previous two terms. By starting with 1 and 2, the first 10 
terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.

*/

function sum2fibs(below){
    let sum = 0;
    let prev2 = 1;
    let prev1 = 1;
    let fib=prev2+prev1;

    console.log(`inside sumfib( below: ${below}`);
    console.log(`fibs:`);

    while( fib<below ) {
        if( fib%2 == 0 ) {
            sum += fib;
            console.log(`  ${fib} *** sum: ${sum}`);
        }
        else{
            console.log(`  ${fib}`);
        }
        prev2 = prev1;
        prev1 = fib;
        fib = prev2 + prev1;
    }

    return sum;

}
let target = 4000000;
let ret = sum2fibs(target);
console.log('Ans: ', ret);